// styles.js
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#C2FFD3',
        alignItems: 'center',
    },
    text: {
        color: '#D7D7D9',
        fontSize: 15,
        fontFamily: 'Kanit_400Regular',
    },
    krop: {
        width: '90%',
        height: '20%',
        backgroundColor: 'white',
        borderRadius: 15,
        alignItems: 'center',
        marginTop: 15,
    },
    circleTopic: {
        width: 120,
        height: 120,
        borderRadius: 100,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 7,
        borderColor: '#005B34',
        marginTop: 10,
    },
    container2: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'flex-start',
        gap: 10,
        flexDirection: 'row',
        marginTop: 8,
    },
    circle: {
        width: 80,
        height: 80,
        borderRadius: 75,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 7,
        borderColor: '#FF88F3',
    },
    fatCircle: {
        width: 80,
        height: 80,
        borderRadius: 75,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 7,
        borderColor: '#FFE68C',
    },
    carbCircle: {
        width: 80,
        height: 80,
        borderRadius: 75,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 7,
        borderColor: '#A6E4FF',
    },
    fibrtCircle: {
        width: 80,
        height: 80,
        borderRadius: 75,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 7,
        borderColor: '#56F08A',
    },
    buttonText1: {
        fontSize: 18,
        color: '#958E8F',
        fontFamily: 'Kanit_400Regular',
    },

    buttonTextTopic: {
        fontSize: 20,
        color: '#006212',
        fontFamily: 'Kanit_400Regular',
    },

    mealContainer: {
        alignItems: 'center',
        marginTop: 5,
    },

    topic : {
        alignItems: 'center',
        marginTop: 55,
    },

    mealRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 5,
    },
    mealImage: {
        width: 80,
        height: 80,
        marginBottom: 10,
    },
    mealHeaderText: {
        fontSize: 20,
        fontFamily: 'Kanit_400Regular',
        color: '#C4C4D5',
        marginBottom: 12,
        alignItems: 'center'
    },
    buttonText: {
        color: 'white',
        fontSize: 16,
        fontFamily: 'Kanit_400Regular',
    },
    Text: {
        color: 'green',
        fontSize: 16,
        fontFamily: 'Kanit_400Regular',
        alignItems: 'flex-start',
    },
    Title: {
        color: 'green',
        fontSize: 25,
        fontFamily: 'Kanit_400Regular',
        alignItems: 'center',
    },
    style: {
        width: '90%',
        height: '15%',
        backgroundColor: 'white',
        borderRadius: 15,
        marginTop: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 30,
        marginTop: 2,
        fontFamily: 'Kanit_400Regular',
    },

    editButtonText: {
        color: 'white',
        fontSize: 12,
        justifyContent: 'center',
        fontFamily: 'Kanit_400Regular',
    },
    input: {
        width: '100%',
        height: 40,
        backgroundColor: '#D0D0ED',
        borderRadius: 5,
        paddingHorizontal: 10,
        marginBottom: 20,
        fontFamily: 'Kanit_400Regular',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'black',
    },
    modalContent: {
        backgroundColor: 'white',
        borderRadius: 10,
        padding:20,
        width: '100%',
        height: '110%',
    },
    closeModalButton: {
        backgroundColor: '#CC0000',
        paddingVertical: 5,
        paddingHorizontal: 12,
        borderRadius: 50,
        marginTop: 10,
        justifyContent: 'center',
        marginBottom: 10,
    },
    deleteItem: {
        backgroundColor: '#FF8888',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 5,
        marginTop: 10,
        justifyContent: 'center'
    },
    editButton: {
        backgroundColor: '#52B788',
        paddingVertical: 4,
        paddingHorizontal: 10,
        borderRadius: 5,
        justifyContent: 'center',
    },
    editButtonText: {
        color: 'white',
        fontSize: 12,
        justifyContent: 'center',
        fontFamily: 'Kanit_400Regular',
    },
    recordButton: {
        backgroundColor: '#52B788',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 5,
        justifyContent: 'center'
    },
    buttonText: {
        color: 'white',
        fontSize: 16,
        fontFamily: 'Kanit_400Regular',
        textAlign: 'center',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    closeModalButton: {
        backgroundColor: '#CC0000',
        paddingVertical: 5,
        paddingHorizontal: 12,
        borderRadius: 50,
        marginTop: 10,
        justifyContent: 'center',
        marginBottom: 10,
    },
    button: {
        width: '100%',
        height: 30,
        backgroundColor: '#52B788',
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: '10%',
      },
      buttonDetail: {
        width: '30%',
        height: 30,
        backgroundColor: '#D9D9D9',
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: '1%',
      },
    buttonTextDetail: {
        color: '#C8C8C8',
        fontSize: 16,
        fontFamily: 'Kanit_400Regular',
        textAlign: 'center',
    },
    buttonText: {
        color: 'white',
        fontSize: 16,
        fontFamily: 'Kanit_400Regular',
        textAlign: 'center',
    },
    input: {
        width: '100%',
        height: 40,
        backgroundColor: '#FFFFFF',
        borderRadius: 5,
        paddingHorizontal: 10,
        marginBottom: 20,
        fontFamily: 'Kanit_400Regular',
    },
    tabMenu: {
        flexDirection: 'row',
        marginBottom: 5,
        fontFamily: 'Kanit_400Regular',
    },
    tab: {
        width: '40%',
        padding: 10,
        backgroundColor: '#ccc',
        marginHorizontal: 5,
        borderRadius: 5,
        fontFamily: 'Kanit_400Regular',
        justifyContent: 'center',
        alignItems: 'center',
    },
    activeTab: {
        backgroundColor: '#52B788',
    },
    tabText: {
        color: 'white',
        fontFamily: 'Kanit_400Regular',
    },
    circle1: {
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 15,
    },
    circle2: {
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 15,
        padding: 10,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        backgroundColor: 'white',
        borderColor: '#E4E4E4',
        borderRadius: 30,
        paddingHorizontal: 10,
        fontSize: 20,
        height: 52,
        width: '100%',
        marginTop: 10,
        marginBottom: 10,
        fontFamily: 'Kanit_400Regular',
    },
    modalSearchContent: {
        alignItems: 'center',
        backgroundColor: 'white',
        padding: 20,
        borderRadius: 10,
        width: '100%',
        height: '70%',
    },
    buttonSearhSave: {
        width: '90%',
        height: 50,
        backgroundColor: '#52B788',
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 15,
    },

    Nu1:
    {
        flexDirection: 'row', 
        justifyContent: 'space-between', 
        marginTop: 15, backgroundColor: '#FFD5FB', 
        borderRadius: 100, 
        width: '100%', height: '7%', alignItems: 'center'
    },
});

export default styles;